Repository apache/flink-connector-jdbc, pull requests merged in 2023-02, with the labels that each got.

#19 [FLINK-30880] Update flink version to 1.16.1
  .github/workflows/push_pr.yml
  pom.xml
Labels: component=BuildSystem

#21 [FLINK-30963][ci] Streamline binary URL configuration
  .github/workflows/push_pr.yml
  .github/workflows/weekly.yml
Labels: component=BuildSystem

#23 [hotfix][doc] Fix the description about lookup.max-retries in the zh docs
  docs/content.zh/docs/connectors/table/jdbc.md
Labels: component=Documentation

#24 [FLINK-31181] Support LIKE operator pushdown
  flink-connector-jdbc/src/main/java/org/apache/flink/connector/jdbc/table/JdbcFilterPushdownPreparedStatementVisitor.java
  flink-connector-jdbc/src/test/java/org/apache/flink/connector/jdbc/table/JdbcFilterPushdownPreparedStatementVisitorTest.java
Labels: component=Connectors/JDBC
